### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [AliRN9/polygon#1]
1) Первое задание зачтено.

2) Во втором задании ошибка: когда точка не совпадает с вершиной, не лежит на стороне и не лежит внутри, то возвращаемое значение функции не определено. Второе задание пока не зачтено.

3) Нет обработок ошибок ввода аргументов командной строки и ошибок в файле, не используется перечислимый тип, третье задание не зачтено.

**Comment by AliRN9** [comment]
добрый вечер
я все починил и добавил обработку ошибок

**Comment by dzheltkov** [comment]
Задания 2-3 зачтены.
